apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: api
          image: hashicorp/http-echo:latest
          args:
            - '-text={"status": "success", "mensaje": "Hola desde la API de Backend en Kubernetes!"}'
          ports:
            - containerPort: 5678
